dns_ip: "1.1.1.1"

xray:
  enabled: true
  port: 10134

trojan:
  enabled: false
  port: 10130

users:
  - name: "root"
    password: "PASSWORD"

reality:
  server: "telegram.org"
  port: 443
  short_id: "DEADBEEF"
