- name: Install required packages
  hosts: all
  tasks:
   - name: Check if sing-box is installed
     command: 'which sing-box'
     become: false
     register: res
     ignore_errors: yes

   - name: Install sing-box
     become: true
     when: res.rc != 0
     block:
       - name: Add sing-box key
         ansible.builtin.get_url:
           url: https://sing-box.app/gpg.key
           dest: /etc/apt/keyrings/sagernet.asc
           checksum: sha256:803d5a2f09fe9d360008161aa2684e7f49a211d48a4116d0651b08bdd90bdea1

       - name: Get architecture
         command: "dpkg --print-architecture"
         register: arch

       - name: Configure apt source
         ansible.builtin.apt_repository:
           repo: "deb [arch={{ arch.stdout }} signed-by=/etc/apt/keyrings/sagernet.asc] https://deb.sagernet.org/ * *"
           state: present

       - name: Install sing-box package
         ansible.builtin.apt:
           name: sing-box

   - name: Enable service
     become: true
     ansible.builtin.systemd:
       name: sing-box
       enabled: true
       masked: no
