- name: Configure sing-box server
  hosts: all
  vars_files:
    - config.yml
  tasks:
    - name: Preliminary config check
      ansible.builtin.assert:
        that:
          - "item.password != 'PASSWORD'"
        msg: Please set user password in config.yml
        quiet: true
        success_msg: "Passwords are valid"
      loop: "{{ users }}"
    
    - name: Generate xray reality privkey
      command: "sing-box generate reality-keypair"
      register: keypair_out
      when: xray.enabled

    - name: Parse privkey and pubkey
      set_fact:
        reality_privkey: "{{ keypair_out.stdout_lines | select('regex', 'PrivateKey+') | first | split() | last }}"
        reality_pubkey: "{{ keypair_out.stdout_lines | select('regex', 'PublicKey+') | first | split() | last }}"
      when: xray.enabled

    - name: Create backup dir
      ansible.builtin.file:
        path: /etc/sing-box/backup
        state: directory

    - name: Backup old config file
      ansible.builtin.copy:
        src: /etc/sing-box/config.json
        dest: /etc/sing-box/backup/config_backup.json
        backup: true
        remote_src: true

    - name: Generate config from template
      template:
        src: template.j2
        dest: /etc/sing-box/config.json

    - name: Check generated configuration
      ansible.builtin.command: sing-box check -c /etc/sing-box/config.json
      register: res
      failed_when: res.stdout != "" or res.stderr != "" 

    - name: Restart service
      ansible.builtin.systemd:
        name: sing-box
        state: restarted

    - name: Print generated variables
      ansible.builtin.debug:
        msg:
          - "GENERATED_PUBKEY: {{ reality_pubkey }}"
          - "Please write it down"
      when: xray.enabled
